[build]
publish = "dist"

[[redirects]]
  from = "/openfoodapi/*"
  to = "https://world.openfoodfacts.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200